services:
  - type: web
    name: marketing-app
    env: python
    region: oregon  # or any other region like frankfurt
    buildCommand: |
      cd frontend && yarn install && yarn start
      cd ../backend && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
